name: Development

# on: 어떤 상황에서 workflows를 실행시킬것인가? 이벤트
on:
  # add a push event that trigggers this workflow
  push:
    branches:
      - main

# job 하나하나가 빌드서버 하나하나 생성
jobs:
  build-test: # dictionary임. 따라서 job들은 순서대로 실행되지 않음
    runs-on: ubuntu-latest

    # 어떤 단계로..
    steps:
      - name: Step 1
        run: # run command

      - name: Step 2
        run: # run command

      # add a new step to checkout the code
      # 깃허브.com/actions/checkout@v2 들어가보면 나옴(공식 액션)
      - name: Checkout code
        uses: actions/checkout@v2

      # add a new step to install .NET SDK 7
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.x

      # add a new step to restore nuget packages
      - name: Restore nuget packages
        run: dotnet restore

      # # add a new step to build the entire solution
      # - name: Build solution
      #   run: dotnet build

      # # add a new step to test the solution
      # - name: Test solution
      #   run: dotnet test

      # add a new step to build the entire solution with Release configuration
      - name: Build
        run: dotnet build --configuration Release

      # add a new step to test the solution with Release configuration
      - name: Test
        run: dotnet test --configuration Release

      # add a new step to publish src/WebApi with Release configuration
      # 솔루션 전체 하면 테스트코드도 들어가므로, 특정 경로만.. publish
      - name: Publish
        run: dotnet publish src/WebApi --configuration Release --output publish
      # 이 아티팩트?를 배포하는 것.

      




      # Add more steps as needed
